version: '3.9'
services:
  hoyolab_bot:
    container_name: hoyolab_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-.env.production}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
