version: '3.9'
services:
  hoyolab_bot:
    container_name: hoyolab_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE:-.env.production}
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: npm run start
    networks:
      - monitoring

networks:
    monitoring:
        external: true
