name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.52.0

      - name: Wait for Tailscale to Connect
        run: sleep 10

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.PI_TAILSCALE_IP }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          script: |
            cd /home/bots/Dailycheckin_Bot
            git pull origin main  
            docker-compose down  
            docker-compose up -d --build
