name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.52.0

      - name: Wait for Tailscale to Connect
        run: sleep 10

      - name: Debug Tailscale Connection
        run: |
          tailscale status
          tailscale ip -4
          ping -c 4 potat
          ping -c 4 ${{ secrets.PI_TAILSCALE_IP }}

      - name: Debug SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.PI_TAILSCALE_IP }} 'echo "SSH connection successful"'
        env:
          PI_SSH_KEY: ${{ secrets.PI_SSH_KEY }}    

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.PI_TAILSCALE_IP }}
          username: root
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          script: |
            cd /home/bots/Dailycheckin_Bot
            git pull origin main  
            docker-compose down  
            docker-compose up -d --build
            cd /home/bots/Dailycheckin_Bot
            git pull origin main  
            docker-compose down  
            docker-compose up -d --build
