name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.52.0

      - name: Wait for Tailscale to Connect
        run: sleep 10  

      - name: Write SSH Key to File
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Host to Known Hosts
        run: |
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.PI_TAILSCALE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy bot with Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.PI_TAILSCALE_IP }} 'cd /home/bots/Dailycheckin_Bot && git pull origin main && docker compose down && docker compose up -d --build'
