name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Authenticate Tailscale
        run: sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Wait for Tailscale to Connect
        run: sleep 10

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.PI_TAILSCALE_IP }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          script: |
            cd /home/bots/Dailycheckin_Bot
            git pull origin main  
            docker-compose down  
            docker-compose up -d --build