name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Create .env file for testing
        run: echo "ENCRYPTION_KEY=fake_testing_key_32_chars" > .env.encryption

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test