name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BOT_ADMIN_ID: ${{ vars.BOT_ADMIN_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          METRICS_PORT: ${{ vars.METRICS_PORT }}
        run: npm test

    environment:
      name: Tests
